INSERT INTO News (judul, isi_konten, id_author) VALUES
('Turnamen Dimulai','Liga resmi dimulai minggu ini',1),
('Match Seru Hari Ini','Pertandingan berlangsung sengit',1),
('Grand Final Soon','Final akan digelar minggu depan',1),
('Patch Baru Dirilis','Update terbaru membawa perubahan meta',1),
('Team Garuda Menang','Garuda Esports tampil dominan',1),
('Nusantara Comeback','Kemenangan dramatis terjadi',1),
('Phoenix Tampil Solid','Strategi mereka sangat rapi',1),
('Rajawali Bangkit','Tim menunjukkan performa meningkat',1),
('Highlight Mingguan','Kumpulan momen terbaik minggu ini',1),
('Top Player Week 1','Player terbaik minggu pertama diumumkan',1),
('Update Jadwal','Perubahan jadwal pertandingan terbaru',1),
('Analisis Match','Breakdown strategi pertandingan',1),
('Roster Update','Perubahan roster tim diumumkan',1),
('Player Cedera','Salah satu pemain absen sementara',1),
('Map Favorit','Map yang paling sering dimainkan',1),
('Statistik Turnamen','Data performa seluruh tim',1),
('Interview Player','Wawancara eksklusif pemain',1),
('Semi Final Recap','Ringkasan pertandingan semifinal',1),
('Final Preview','Prediksi pertandingan final',1),
('Champion Crowned','Juara turnamen resmi diumumkan',1);