INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (1, 1, 'f0rsakeN', 'Indonesia', 'Flex', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (2, 1, 'Jinggg', 'Singapore', 'Duelist', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (3, 1, 'something', 'Russia', 'Duelist', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (4, 1, 'd4v41', 'Malaysia', 'Initiator', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (5, 1, 'invy', 'Philippines', 'Controller', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (6, 2, 'xffero', 'Indonesia', 'Controller', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (7, 2, 'Lmemore', 'Indonesia', 'Sentinel', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (8, 2, 'Estrella', 'South Korea', 'Initiator', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (9, 2, 'Jemkin', 'Russia', 'Duelist', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (10, 2, 'Monyet', 'Indonesia', 'Flex', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (11, 3, 'aspas', 'Brazil', 'Duelist', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (12, 3, 'kiNgg', 'Chile', 'Controller', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (13, 3, 'tex', 'USA', 'Sentinel', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (14, 3, 'Mazino', 'Chile', 'Flex', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (15, 3, 'C0M', 'USA', 'Initiator', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (16, 4, 'OXY', 'USA', 'Duelist', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (17, 4, 'vanity', 'USA', 'Controller', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (18, 4, 'xeppaa', 'USA', 'Initiator', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (19, 4, 'moose', 'USA', 'Sentinel', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (20, 4, 'runi', 'USA', 'Flex', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (21, 5, 'sayf', 'Sweden', 'Duelist', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (22, 5, 'trexx', 'Russia', 'Initiator', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (23, 5, 'Kicks', 'Finland', 'Flex', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (24, 5, 'runneR', 'Macedonia', 'Sentinel', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (25, 5, 'ceNder', 'Lithuania', 'Controller', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (26, 6, 'whzy', 'China', 'Duelist', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (27, 6, 'yosemite', 'China', 'Sentinel', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (28, 6, 'Knight', 'China', 'Initiator', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (29, 6, 'biank', 'China', 'Flex', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (30, 6, 'B3Ar', 'China', 'Controller', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (31, 7, 'Ethan', 'United States', 'Initiator', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (32, 7, 'mada', 'Canada', 'Duelist', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (33, 7, 'skuba', 'United States', 'Controller', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (34, 7, 'keiko', 'United Kingdom', 'Duelist', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (35, 7, 'brawk', 'United States', 'Initiator', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (36, 8, 'Kai', 'China', 'Initiator', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (37, 8, 'LuoK1ng', 'China', 'Controller', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (38, 8, 'FengF', 'China', 'Duelist', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (39, 8, 'Viva', 'China', 'Flex', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (40, 8, 'deLb', 'China', 'Duelist', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (41, 9, 'WsLeo', 'Taiwan', 'Initiator', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (42, 9, 'Lysoar', 'China', 'Sentinel', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (43, 9, 'NoMan', 'Hong Kong', 'Controller', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (44, 9, 'coconut', 'Hong Kong', 'Flex', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (45, 9, 'happywei', 'Taiwan', 'Initiator', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (46, 10, 'nAts', 'Russia', 'Sentinel', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (47, 10, 'wayne', 'Singapore', 'Flex', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (48, 10, 'MiniBoo', 'Lithuania', 'Duelist', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (49, 10, 'purp0', 'Russia', 'Duelist', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (50, 10, 'kamo', 'Poland', 'Duelist', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (51, 11, 'Munchkin', 'South Korea', 'Initiator', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (52, 11, 'BuZz', 'South Korea', 'Duelist', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (53, 11, 'Meteor', 'South Korea', 'Sentinel', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (54, 11, 'Stax', 'South Korea', 'Initiator', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (55, 11, 'iZu', 'South Korea', 'Controller', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (56, 12, 'Crewen', 'Turkey', 'Sentinel', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (57, 12, 'Lar0k', 'Turkey', 'Controller', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (58, 12, 'Loita', 'Turkey', 'Initiator', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (59, 12, 'Rosé', 'Turkey', 'Flex', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (60, 12, 'umu7', 'Turkey', 'Sentinel', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (61, 13, 'zekken', 'United States', 'Duelist', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (62, 13, 'johnqt', 'Morocco', 'Sentinel', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (63, 13, 'N4RRATE', 'United States', 'Initiator', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (64, 13, 'bang', 'United States', 'Controller', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (65, 13, 'Zellsis', 'United States', 'Flex', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (66, 14, 'Boaster', 'United Kingdom', 'Controller', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (67, 14, 'Derke', 'Finland', 'Duelist', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (68, 14, 'Alfajer', 'Turkey', 'Sentinel', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (69, 14, 'Chronicle', 'Russia', 'Flex', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (70, 14, 'Leo', 'Sweden', 'Initiator', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (71, 15, 'Spring', 'China', 'Duelist', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (72, 15, 'pl1xx', 'Australia', 'Flex', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (73, 15, 'ColdFish', 'China', 'Controller', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (74, 15, 'Yuicaw', 'China', 'Sentinel', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (75, 15, 'aluba', 'China', 'Initiator', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (76, 16, 'ZmjjKK', 'China', 'Duelist', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (77, 16, 'CHICHOO', 'China', 'Sentinel', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (78, 16, 'nobody', 'China', 'Initiator', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (79, 16, 'Smoggy', 'China', 'Flex', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (80, 16, 'S1Mon', 'South Korea', 'Initiator', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (81, 17, 'AAAAY', 'China', 'Initiator', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (82, 17, 'BerLIN', 'Taiwan', 'Controller', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (83, 17, 'Life', 'China', 'Duelist', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (84, 17, 'autumn', 'Australia', 'Flex', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (85, 17, 'TzH', 'China', 'Sentinel', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (86, 18, 'monk', 'China', 'Duelist', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (87, 18, 'deicide', 'China', 'Initiator', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (88, 18, 'spitfires', 'China', 'Flex', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (89, 18, 'bunt', 'China', 'Sentinel', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (90, 18, 'sword9', 'China', 'Controller', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (91, 19, 'BlackWiz', 'Japan', 'Controller', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (92, 19, 'xnfri', 'Japan', 'Initiator', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (93, 19, 'JoXJo', 'South Korea', 'Initiator', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (94, 19, 'Liaz', 'Japan', 'Sentinel', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (95, 19, 'zepher', 'Japan', 'Duelist', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (96, 20, 't3xture', 'South Korea', 'Duelist', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (97, 20, 'Lakia', 'South Korea', 'Initiator', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (98, 20, 'Karon', 'South Korea', 'Controller', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (99, 20, 'yoman', 'South Korea', 'Sentinel', null);
INSERT INTO players (id_player, id_teams, nama, country, role, photo_url) VALUES (100, 20, 'foxy9', 'South Korea', 'Flex', null);

-- Menyelaraskan ulang urutan auto-increment ID untuk tabel players
SELECT setval(pg_get_serial_sequence('players', 'id_player'), COALESCE(MAX(id_player), 1)) FROM players;