INSERT INTO public.news (judul,isi_berita,publisher,tanggal,featured,thumbnail_url) VALUES
	 ('Tenz Retirement','After years of dominating the server and redefining what it means to be a superstar in Valorant, Tyson "TenZ" Ngo has officially announced his retirement from competitive play. The Sentinels legend, who became the global face of the game during its early days, is hanging up his mouse to focus fully on streaming and content creation. TenZ journey in Valorant is nothing short of iconic. From leading Sentinels to a flawless, map-undefeated victory at Masters Reykjavik in 2021, to his incredible redemption arc winning Masters Madrid in 2024, his mechanical brilliance and flashy plays have inspired millions of players worldwide. While fans will deeply miss seeing him compete on the main stage, TenZ expressed that he is at peace with his decision and ready for the next chapter of his life. He steps away not just as a two-time international champion, but as one of the most influential players in esports history. The competitive scene wont be the same without him, but his legacy in Valorant is permanently secured','admin_meta','2026-06-04 05:41:15.08104',false,NULL),
	 ('Nongshim Red Force make a legendary history','Nongshim Red Force has etched their names into the Valorant history books following a monumental and completely unexpected championship run. Entering the tournament as underdogs, the squad faced immense pressure and skeptical predictions from analysts worldwide. However, through sheer mechanical brilliance and an unbreakable team synergy, they managed to overcome the odds, taking down the region''s absolute giants in a spectacular fashion.

This legendary victory has sent shockwaves through the competitive scene, proving that tactical discipline and relentless grit can triumph over established powerhouses. The historic win not only secures their trophy but also cements Nongshim Red Force as a true powerhouse to be feared in future international events. Fans are still celebrating what many are already calling the greatest Cinderella story in recent esports history.','admin_meta','2026-06-04 07:28:05.897762',false,NULL),
	 ('M80 Statement','M80 management has released a comprehensive and highly anticipated official statement outlining the organization''s strategic vision for its competitive Valorant division moving forward. The announcement addresses recent performance fluctuations and details internal adjustments aimed at restructuring the core dynamics of the team. Rather than looking back, the organization emphasizes a forward-thinking mentality designed to foster long-term stability and success.

In the statement, M80 expressed deep gratitude to their loyal fanbase for their unwavering support during this transitional period. They reaffirmed their core commitment to providing the roster with top-tier resources, coaching staff, and analytical support necessary to reclaim their spot at the top of the leaderboards. With these systemic changes underway, the squad is fully focused on rigorous preparation for the demanding qualifiers ahead.','admin_meta','2026-06-04 07:28:05.897762',false,NULL),
	 ('Paper Rex and Team Liquid Smoothly qualifies into playoffs','Heavyweights Paper Rex and Team Liquid have comfortably secured their spots in the next stage of the tournament after putting on an absolute masterclass on the server. Both teams completely dismantled their respective opponents, showing an elite level of tactical preparation and clinical execution that left no room for error. Their flawless group stage runs have sent a clear and intimidating message to the rest of the competition.

Paper Rex thrilled fans with their trademark chaotic, fast-paced aggression, while Team Liquid demonstrated an incredibly disciplined and immovable defensive protocol. As the tournament shifts towards the high-stakes bracket stages, both squads look entirely unstoppable and are heavily favored to make it all the way to the grand finals. Opponents will need to completely reinvent their strategies if they hope to disrupt the momentum of these two juggernauts.','admin_meta','2026-06-04 07:28:05.897762',false,NULL),
	 ('T1 And NRG Barely made it into playoffs','In a dramatic and nerve-wracking conclusion to the group stage, both T1 and NRG have managed to miraculously claw their way into the playoff brackets by the skin of their teeth. Both teams faced a series of grueling, must-win matches and had to rely on complex tiebreaker scenarios after suffering unexpected setbacks earlier in the tournament. The intense pressure was palpable, making every single round a battle for survival.

While their journey to the playoffs was far from perfect and exposed several structural vulnerabilities, their clutch performance under extreme adversity proved their veteran resilience. Coaches from both organizations have acknowledged that there is an immense amount of mistakes to fix before the next round begins. Now that they have survived the group stage crucible, T1 and NRG enter the playoffs as dangerous wildcards with absolutely nothing left to lose.','admin_meta','2026-06-04 07:28:05.897762',false,NULL),
	 ('FNATIC sign Carlotta','FNATIC have officially announced the addition of Carlotta to their active Valorant roster, rounding out their lineup ahead of the upcoming VCT EMEA season.

The move comes after weeks of rumors regarding FNATIC''s final piece. Carlotta arrives following a standout season in the Challengers circuit, where she consistently topped the leaderboards with aggressive entry fragging and high-impact plays. Her addition is expected to bring a fresh, explosive dynamic to the EMEA powerhouse.

"I''m incredibly excited to join an organization with such a massive legacy," Carlotta shared on Twitter shortly after the announcement. "Playing alongside this core is a dream, and I''m ready to prove myself at the highest level."

She will step directly into the starting lineup under the leadership of Boaster. Carlotta is set to make her official debut next week as FNATIC looks to reclaim their spot at the absolute top of the international stage.

FNATIC is now:
Jake "Boaster" Howlett
Leo "Leo" Jannesson
Timofey "Chronicle" Khromov
Emir "Alfajer" Beder
Carlotta "Carlotta" Montelli
Chris "Elmapuddy" Tebbit (Head Coach)','admin_meta','2026-06-04 15:48:12.273326',true,'https://c4.wallpaperflare.com/wallpaper/929/517/204/wuthering-waves-carlotta-wuthering-waves-anime-anime-games-pixiv-hd-wallpaper-preview.jpg'),
	 ('DRX Calls up academy teams player "yong" to main rosters','DRX has officially announced the promotion of academy standout player "yong" to their main Valorant roster ahead of the upcoming VCT stages. The young prodigy caught the attention of the primary coaching staff after delivering a string of breathtaking, high-fragging performances in the tier-two academy circuit. This roster move reflects DRX''s long-standing philosophy of scouting and nurturing raw homegrown talent rather than relying solely on high-profile transfers.

Integrating a rookie into a world-class roster always carries risks, but team veterans have expressed immense excitement about yong''s explosive aim and fresh perspective. Analysts believe his versatile agent pool will give DRX a much-needed layer of unpredictability in complex map vetoes. As yong steps onto the grand international stage, all eyes will be on him to see if he can translate his academy dominance into tier-one victory.','admin_meta','2026-06-04 07:28:05.897762',false,NULL),
	 ('FunPlusPhoenix sign "Sacy" to the squad','FunPlusPhoenix (FPX) has shocked the international Valorant community by officially signing Gustavo "Sacy" Rossi to their main roster. The former world champion brings an unparalleled level of experience, tactical depth, and leadership to a squad looking to establish dominance in their region. This unexpected transfer marks a massive strategic shift for FPX as they look to blend Sacy''s veteran composure with their existing explosive playstyle.

Fans and analysts are eager to see how Sacy''s legendary initiator play will revitalize FPX''s coordination in upcoming high-stakes tournaments. Management expressed ultimate confidence in this signing, stating that adding a player of his caliber is exactly what the team needs to push past their previous limits. The pressure is on, but with a world-class champion now in the server, FPX is shaping up to be one of the most formidable contenders this season.','admin_meta','2026-06-04 00:00:00',false,NULL);
